// these were generated by ChatGPT just to have some test data.
// probably don't try actually following these.
export default [
  {
    "author": "Alex Rivera",
    "name": "Savory Pumpkin Soup",
    "description": "this dish brings back memories of my grandmother's kitchen in the fall. every year, we'd gather to help her prepare this hearty soup using pumpkins from our garden. it's a warm, comforting dish that's become a tradition in our family",
    "prepTime": 30,
    "cookTime": 45,
    "ingredients": [
      "one large onion",
      "4 carrots",
      "2 cups pumpkin puree",
      "3 cloves garlic",
      "1 quart vegetable broth",
      "1 cup cream",
      "salt and pepper to taste"
    ],
    "steps": [
      "dice the onion and carrots",
      "saute the onion, carrots, and minced garlic until soft",
      "add the pumpkin puree and vegetable broth and bring to a boil",
      "reduce heat and simmer for 30 minutes",
      "blend the soup until smooth",
      "stir in cream and season with salt and pepper",
      "heat through and serve hot"
    ]
  },
  {
    "author": "Chris Yamamoto",
    "name": "Teriyaki Chicken",
    "description": "learned this recipe while living in Tokyo. my neighbors taught me the importance of balancing the sweet and savory aspects of teriyaki sauce to enhance the flavor of the chicken",
    "prepTime": 20,
    "cookTime": 20,
    "ingredients": [
      "2 lbs chicken thighs",
      "1/2 cup soy sauce",
      "1/4 cup mirin",
      "1/4 cup sake",
      "2 tablespoons sugar",
      "1 inch ginger, grated",
      "1 clove garlic, minced"
    ],
    "steps": [
      "cut chicken into bite-sized pieces",
      "mix soy sauce, mirin, sake, sugar, ginger, and garlic in a bowl",
      "marinate the chicken in the mixture for at least an hour",
      "heat a pan over medium-high and cook the chicken until golden brown",
      "reduce the sauce in the pan until thickened and coat the chicken evenly"
    ]
  },
  {
    "author": "Mia Thompson",
    "name": "Classic Caesar Salad",
    "description": "the story behind this recipe starts with a rainy day in a small cafe in Rome where i discovered the perfect Caesar salad. inspired, i sought to recreate it with my own twist back home",
    "prepTime": 15,
    "cookTime": 0,
    "ingredients": [
      "1 head of romaine lettuce",
      "1/2 cup parmesan cheese",
      "1/4 cup croutons",
      "1 egg yolk",
      "1 tablespoon mustard",
      "1 clove garlic",
      "juice of 1 lemon",
      "anchovies (optional)"
    ],
    "steps": [
      "wash and chop the lettuce",
      "mix the egg yolk, mustard, minced garlic, and lemon juice to make the dressing",
      "toss the lettuce with the dressing",
      "add croutons and shaved parmesan",
      "top with anchovies if using"
    ]
  },
  {
    "author": "John Hart",
    "name": "Beef Stew",
    "description": "this recipe has been passed down through generations in my family. it's a filling, nutritious meal that epitomizes the concept of a homemade dish, perfect for cold weather",
    "prepTime": 20,
    "cookTime": 120,
    "ingredients": [
      "2 lbs beef chuck",
      "1 large onion",
      "4 carrots",
      "2 potatoes",
      "4 cups beef broth",
      "1 cup red wine",
      "2 tablespoons tomato paste",
      "salt and pepper to taste",
      "2 bay leaves"
    ],
    "steps": [
      "cut beef into 1-inch cubes",
      "brown the beef in a large pot",
      "dice the onion, carrots, and potatoes and add to the pot",
      "pour in the beef broth and red wine",
      "stir in the tomato paste",
      "season with salt, pepper, and bay leaves",
      "simmer for 2 hours or until the beef is tender"
    ]
  },
  {
    "author": "Linda Schwartz",
    "name": "Vegan Chocolate Cake",
    "description": "this cake changed my mind about vegan desserts. i experimented with various ingredients to replicate the moistness and richness of traditional cakes. the result is a delightful treat that surprises everyone",
    "prepTime": 15,
    "cookTime": 35,
    "ingredients": [
      "2 cups all-purpose flour",
      "1 cup sugar",
      "1/2 cup cocoa powder",
      "1 teaspoon baking soda",
      "1/2 teaspoon salt",
      "1 cup water",
      "1/2 cup vegetable oil",
      "1 tablespoon vinegar",
      "1 teaspoon vanilla extract"
    ],
    "steps": [
      "preheat the oven to 350 degrees F",
      "mix all the dry ingredients together",
      "add the water, oil, vinegar, and vanilla and mix until smooth",
      "pour into a greased cake pan",
      "bake for 35 minutes or until a toothpick comes out clean"
    ]
  },
  {
    "author": "Rebecca Lee",
    "name": "Spaghetti Carbonara",
    "description": "a dish i mastered while on a culinary journey through Italy. this simple, creamy pasta has only a few ingredients but requires precise timing and technique to perfect",
    "prepTime": 10,
    "cookTime": 20,
    "ingredients": [
      "400g spaghetti",
      "200g pancetta",
      "2 large eggs",
      "3/4 cup grated Parmesan cheese",
      "black pepper"
    ],
    "steps": [
      "cook spaghetti al dente",
      "fry pancetta until crisp",
      "whisk together eggs and Parmesan",
      "combine all with pasta off heat to create a creamy sauce",
      "season with plenty of black pepper"
    ]
  },
  {
    "author": "Oliver Smith",
    "name": "Mango Lassi",
    "description": "discovered this refreshing drink during a hot summer in India. it's a perfect blend of sweet and tart, ideal for cooling down",
    "prepTime": 5,
    "cookTime": 0,
    "ingredients": [
      "2 ripe mangoes",
      "2 cups plain yogurt",
      "1/2 cup milk",
      "sugar to taste",
      "a pinch of cardamom"
    ],
    "steps": [
      "peel and dice mangoes",
      "blend mangoes with yogurt, milk, sugar, and cardamom until smooth",
      "serve chilled"
    ]
  },
  {
    "author": "Emily Nguyen",
    "name": "Pho Bo",
    "description": "this traditional Vietnamese beef noodle soup has a rich broth that takes hours to simmer but the complex flavors are worth every minute",
    "prepTime": 30,
    "cookTime": 360,
    "ingredients": [
      "2 lbs beef bones",
      "1 onion, charred",
      "4 cloves garlic, charred",
      "1 piece ginger, charred",
      "3 star anise",
      "1 cinnamon stick",
      "2 lbs brisket",
      "rice noodles",
      "herbs and lime for garnish"
    ],
    "steps": [
      "simmer beef bones in water for 6 hours",
      "add charred onion, garlic, ginger, star anise, and cinnamon",
      "cook brisket in broth until tender",
      "serve over cooked rice noodles",
      "garnish with herbs and lime"
    ]
  },
  {
    "author": "Daniel Kim",
    "name": "Kimchi Fried Rice",
    "description": "this dish is a staple in Korean cooking and features kimchi prominently, which gives it a unique flavor that's both spicy and tangy",
    "prepTime": 10,
    "cookTime": 15,
    "ingredients": [
      "2 cups cooked rice",
      "1 cup kimchi, chopped",
      "1/2 cup kimchi juice",
      "2 eggs",
      "2 green onions",
      "1 tablespoon sesame oil",
      "1 tablespoon soy sauce"
    ],
    "steps": [
      "heat sesame oil in a pan",
      "add chopped kimchi and cook until soft",
      "add rice and kimchi juice, and fry until crispy",
      "make space in the pan, crack eggs into it, and scramble",
      "mix everything together and garnish with chopped green onions"
    ]
  },
  {
    "author": "Nicole Brown",
    "name": "New York Cheesecake",
    "description": "perfected this creamy, dense cheesecake after many trials. it's rich with a graham cracker crust and a smooth cream cheese filling, a classic American dessert",
    "prepTime": 20,
    "cookTime": 90,
    "ingredients": [
      "1 1/2 cups graham cracker crumbs",
      "1/4 cup sugar",
      "1/3 cup melted butter",
      "4 packages cream cheese",
      "1 cup sugar",
      "1 teaspoon vanilla extract",
      "4 eggs",
      "1 cup sour cream"
    ],
    "steps": [
      "combine graham cracker crumbs, sugar, and butter and press into a pan",
      "beat cream cheese, sugar, and vanilla until smooth",
      "add eggs one at a time",
      "pour over crust and bake",
      "cool and top with sour cream"
    ]
  },
  {
    "author": "Rachel Adams",
    "name": "Sourdough Bread",
    "description": "baking sourdough bread is an art and a science. this recipe uses a cultivated starter for a robust flavor and chewy texture",
    "prepTime": 240,
    "cookTime": 50,
    "ingredients": [
      "1 sourdough starter",
      "3 cups all-purpose flour",
      "1 1/2 cups water",
      "1 tablespoon salt"
    ],
    "steps": [
      "mix starter, flour, and water and let sit for 4 hours",
      "add salt and knead dough",
      "let rise until doubled",
      "shape and bake at 450 degrees F for 50 minutes"
    ]
  },
  {
    "author": "Mohamed Ali",
    "name": "Moroccan Tagine",
    "description": "this dish is a feast for the senses, featuring slow-cooked lamb, prunes, and almonds, seasoned with an array of spices. it's a Moroccan classic that brings the flavors of North Africa to your table",
    "prepTime": 15,
    "cookTime": 120,
    "ingredients": [
      "2 lbs lamb shoulder",
      "1 onion, chopped",
      "2 cloves garlic, minced",
      "1 cup prunes",
      "1/2 cup almonds",
      "1 teaspoon cinnamon",
      "1 teaspoon cumin",
      "1/2 teaspoon ginger",
      "2 cups water"
    ],
    "steps": [
      "brown lamb in a tagine or heavy pot",
      "add onions and garlic and cook until soft",
      "add spices and water and bring to a boil",
      "reduce heat to low, add prunes and almonds, and simmer for 2 hours"
    ]
  },
  {
    "author": "Sophia Martinez",
    "name": "Paella Valenciana",
    "description": "this iconic Spanish dish represents the rich culinary heritage of Valencia. it combines seafood, chicken, and vegetables with saffron-infused rice to create a colorful and flavorful meal",
    "prepTime": 20,
    "cookTime": 40,
    "ingredients": [
      "2 cups paella rice",
      "4 cups chicken broth",
      "1 lb chicken thighs, cubed",
      "1/2 lb shrimp, peeled",
      "1/2 lb mussels, cleaned",
      "1 bell pepper, sliced",
      "1/2 cup peas",
      "1 tomato, diced",
      "1 teaspoon saffron threads"
    ],
    "steps": [
      "brown chicken in a paella pan",
      "add bell pepper and tomato and saute",
      "stir in rice, saffron, and broth and bring to a boil",
      "reduce heat and add shrimp and mussels",
      "cook until rice is tender and seafood is cooked"
    ]
  },
  {
    "author": "Isabella Johnson",
    "name": "Ratatouille",
    "description": "inspired by the rustic French countryside, this vegetarian dish is a medley of summer vegetables slow-cooked to perfection. it's healthy, colorful, and bursting with flavor",
    "prepTime": 20,
    "cookTime": 60,
    "ingredients": [
      "1 eggplant",
      "2 zucchinis",
      "1 bell pepper",
      "2 tomatoes",
      "1 onion",
      "3 cloves garlic",
      "1/4 cup olive oil",
      "herbs de Provence"
    ],
    "steps": [
      "slice all vegetables thinly",
      "layer in a baking dish with garlic, onion, and herbs",
      "drizzle with olive oil",
      "bake at 375 degrees F for 60 minutes"
    ]
  },
  {
    "author": "Noah Wilson",
    "name": "Butter Chicken",
    "description": "this dish originates from the heart of Delhi, India. it's a rich and creamy curry that combines tender chicken pieces with a buttery tomato sauce",
    "prepTime": 15,
    "cookTime": 45,
    "ingredients": [
      "2 lbs chicken breast",
      "1 onion, diced",
      "4 cloves garlic, minced",
      "1 inch ginger, minced",
      "1 can tomatoes",
      "1 cup cream",
      "1/4 cup butter",
      "1 tablespoon garam masala",
      "1 teaspoon turmeric",
      "1 teaspoon cumin",
      "1/2 teaspoon chili powder",
      "cilantro for garnish"
    ],
    "steps": [
      "marinate chicken in a mix of yogurt and spices",
      "saute onion, garlic, and ginger in butter",
      "add tomatoes and cook until soft",
      "add marinated chicken and cook until done",
      "stir in cream and simmer until thickened",
      "garnish with cilantro and serve with naan or rice"
    ]
  },
  {
    "author": "Emma Wilson",
    "name": "Maple Glazed Salmon",
    "description": "this dish features a sweet and savory glaze that enhances the natural flavors of the salmon. it's a quick, delicious way to enjoy a healthy meal any night of the week",
    "prepTime": 10,
    "cookTime": 20,
    "ingredients": [
      "4 salmon fillets",
      "1/4 cup maple syrup",
      "2 tablespoons soy sauce",
      "1 clove garlic, minced",
      "1 teaspoon ground ginger",
      "pepper to taste"
    ],
    "steps": [
      "preheat oven to 400 degrees F",
      "mix maple syrup, soy sauce, garlic, and ginger",
      "place salmon in a baking dish",
      "pour glaze over salmon and marinate for 10 minutes",
      "bake for 20 minutes or until salmon flakes easily with a fork"
    ]
  }
]
